DROP TABLE ANGAJAT;

CREATE TABLE ANGAJAT 
(
	  ID NUMBER(*, 0) NOT NULL 
	, COD NVARCHAR2(5) NOT NULL 
	, NUME NVARCHAR2(100) NOT NULL 
	, MEMO NVARCHAR2(500) 
	, CONSTRAINT PK_ANGAJAT PRIMARY KEY(ID)
);  
