drop table ATASAMENT;

CREATE TABLE ATASAMENT
(	
	ID NUMBER(10,0) NOT NULL ENABLE, 
	TITLU NVARCHAR(50 BYTE) NOT NULL ENABLE, 
	URL VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	TIP_FISIER NUMBER(10,0) NOT NULL ENABLE, 
	DT_UPLOAD DATE NOT NULL ENABLE, 
	ANGAJAT NUMBER NOT NULL ENABLE, 
	MEMO NVARCHAR(200 BYTE), 
	constraint PK_ATASAMENT primary key (ID)
);
drop sequence SEQ_ATASAMENT;
create sequence SEQ_ATASAMENT;