drop table ATASAMENT;

CREATE TABLE ATASAMENT
(	
	ID NUMBER(*, 0) NOT NULL, 
	TITLU NVARCHAR2(50) NOT NULL, 
	URL NVARCHAR2(100) NOT NULL, 
	TIP_FISIER NUMBER(10,0) NOT NULL, 
	DT_UPLOAD DATE NOT NULL, 
	ANGAJAT NUMBER NOT NULL, 
	MEMO NVARCHAR2(500), 
	constraint PK_ATASAMENT primary key (ID)
);

drop sequence SEQ_ATASAMENT;
create sequence SEQ_ATASAMENT;