DROP TABLE COTATVA;

CREATE TABLE COTATVA
(
	  ID NUMBER(*, 0) NOT NULL
	, COD NVARCHAR(5) NOT NULL
	, NUME NVARCHAR(50) NOT NULL
	, PROCENT DECIMAL(10, 2) NOT NULL
	, CONSTRAINT PK_COTATVA PRIMARY KEY(ID)
);