DROP TABLE FACTURA;

CREATE TABLE FACTURA
(
	  ID NUMBER(*, 0) NOT NULL
	, SERIE NVARCHAR(5) NOT NULL
	, NUMAR DECIMAL(10, 2)
	, DTEMITERE DATE DEFAULT GETDATE()
	, DTSCADENTA DATE 
	, SUMA DECIMAL(10, 2) NOT NULL
	, TVA DECIMAL(3, 2) NOT NULL
	, DRAFT BOOLEAN NOT NULL
	, CONSTRAINT PK_FACTURA PRIMARY KEY(ID)
);