DROP TABLE MONEDA;

CREATE TABLE MONEDA
(
	  ID NUMBER(*, 0) NOT NULL
	, COD NVARCHAR(3) NOT NULL
	, NUME NVARCHAR(50) NOT NULL
	, IMPLICITA BOOLEAN NOT NULL
	, REFERINTA BOOLEAN NOT NULL
	, CONSTRAINT PK_MONEDA PRIMARY KEY(ID)
);